name: CI IT Security

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  test:
    name: Security IT
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: jvalkeal/setup-maven@v1
      with:
        maven-version: 3.6.2
    - name: Run Security IT
      run: |
        mvn \
          -s .settings.xml \
          -pl spring-cloud-dataflow-server \
          -Dgroups=oauth \
          -Pfailsafe \
          --batch-mode \
          integration-test \
          verify
